FROM jupyter/scipy-notebook:python-3.8.8
RUN set -ex \
   && pip install \
   'prefect==0.14.12' \
   'mlflow==1.14.1' \
   'seldon-core==1.6.0' \
   'dask==2021.7.0' \
   'dask-kubernetes==2021.3.1' \
   'scikit-learn==0.24.2'
